// Target channels to organize into
export const TARGET_CHANNELS = {
  INBOX: 'inbox',
  UI_UX: 'ui-ux',
  WEB: 'web',
  WRITING: 'writing',
  CODE: 'code',
  FRAMEWORKS: 'frameworks',
  INDEX: 'index',
} as const;

// Channel display names (used when creating new channels)
export const CHANNEL_TITLES: Record<string, string> = {
  [TARGET_CHANNELS.INBOX]: 'INBOX',
  [TARGET_CHANNELS.UI_UX]: 'UI/UX',
  [TARGET_CHANNELS.WEB]: 'Web',
  [TARGET_CHANNELS.WRITING]: 'Writing',
  [TARGET_CHANNELS.CODE]: 'Code',
  [TARGET_CHANNELS.FRAMEWORKS]: 'Frameworks',
  [TARGET_CHANNELS.INDEX]: 'INDEX',
};

// URL patterns for classification
export const URL_PATTERNS: Record<string, string[]> = {
  [TARGET_CHANNELS.UI_UX]: [
    'mobbin.com',
    'dribbble.com',
    'behance.net',
    'figma.com',
    'pttrns.com',
    'uimovement.com',
    'collectui.com',
    'screenlane.com',
    'pageflows.com',
    'uxarchive.com',
  ],
  [TARGET_CHANNELS.WEB]: [
    'awwwards.com',
    'siteinspire.com',
    'httpster.net',
    'onepagelove.com',
    'lapa.ninja',
    'landings.dev',
    'landingfolio.com',
    'saaslandingpage.com',
    'godly.website',
    'minimal.gallery',
    'hoverstat.es',
    'siiimple.com',
    'webdesign-inspiration.com',
  ],
  [TARGET_CHANNELS.WRITING]: [
    'substack.com',
    'medium.com',
    'longreads.com',
    'theatlantic.com',
    'newyorker.com',
    'aeon.co',
    'nautil.us',
    'lrb.co.uk',
    'nytimes.com',
    'theguardian.com',
    'stratechery.com',
    'ribbonfarm.com',
  ],
  [TARGET_CHANNELS.CODE]: [
    'github.com',
    'gitlab.com',
    'npmjs.com',
    'pypi.org',
    'stackoverflow.com',
    'dev.to',
    'css-tricks.com',
    'smashingmagazine.com',
    'hackernews.com',
    'lobste.rs',
    'codepen.io',
    'codesandbox.io',
    'replit.com',
  ],
  [TARGET_CHANNELS.FRAMEWORKS]: [
    'fs.blog',
    'lesswrong.com',
    'gwern.net',
    'wikipedia.org',
    'stanford.edu',
    'mit.edu',
    'hbr.org',
    'mckinsey.com',
    'bcg.com',
    'firstround.com',
    'a16z.com',
    'ycombinator.com',
  ],
};

// Keywords for content-based classification (checked in title/description)
export const CONTENT_KEYWORDS: Record<string, string[]> = {
  [TARGET_CHANNELS.UI_UX]: [
    'ui',
    'ux',
    'interface',
    'mobile app',
    'ios',
    'android',
    'component',
    'design system',
    'user experience',
    'interaction',
    'prototype',
    'wireframe',
    'mockup',
    'onboarding',
    'signup',
    'login',
    'dashboard',
    'modal',
    'navigation',
  ],
  [TARGET_CHANNELS.WEB]: [
    'landing page',
    'website',
    'homepage',
    'portfolio',
    'web design',
    'hero section',
    'footer',
    'header',
    'layout',
    'responsive',
    'e-commerce',
    'saas',
  ],
  [TARGET_CHANNELS.WRITING]: [
    'essay',
    'article',
    'writing',
    'prose',
    'copywriting',
    'storytelling',
    'narrative',
    'voice',
    'tone',
    'rhetoric',
    'persuasion',
    'longform',
    'editorial',
  ],
  [TARGET_CHANNELS.CODE]: [
    'code',
    'programming',
    'developer',
    'api',
    'library',
    'framework',
    'typescript',
    'javascript',
    'python',
    'react',
    'node',
    'backend',
    'frontend',
    'database',
    'architecture',
  ],
  [TARGET_CHANNELS.FRAMEWORKS]: [
    'framework',
    'mental model',
    'strategy',
    'thinking',
    'decision',
    'principle',
    'philosophy',
    'methodology',
    'process',
    'system',
    'heuristic',
    'cognitive',
    'bias',
    'rationality',
  ],
};

